name: CI
on:
  push:
    branches:
      - main
      - test
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          # Make the image available in next step
          load: true
          tags: ghcr.io/codewars/factor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Passing Example
        run: bin/run passing

      - name: Report Postbuild Info
        run: bin/info >> $GITHUB_STEP_SUMMARY

      - name: Report Image Size
        run: |
          echo "## Image Size" >> $GITHUB_STEP_SUMMARY
          docker image inspect --format '{{.Size}}' ghcr.io/codewars/factor:latest | numfmt --to=si --suffix=B >> $GITHUB_STEP_SUMMARY
